server:
  port: 6002 # 服务端口

eureka:
  instance:
    hostname:  localhost # eureka服务端的实例名称 点击后缀会通过当前ip地址访问
    instance-id: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名称

  client:
    registerWithEureka: true  # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: true # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl:    # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群版
      defaultZone:  http://localhost:6003/eureka/
  server:
    enable-self-preservation: true # 禁用自我保护机制
spring:
  application:
    name: elastic-pay